### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by firefly-cpp** [lukapecnik/NiaAML#13]
Hi @lukapecnik ,

please prepare also a new folder for examples in a similar way that we created for [NiaPy.](https://github.com/NiaOrg/NiaPy/tree/master/examples)

**Comment by lukapecnik** [comment]
Hi @firefly-cpp ,

I will provide folder with examples in the following days. I also need to fix the basic example in the documentation and README.md as it currently does not work because of the changes that were made in the data readers.

**Comment by firefly-cpp** [comment]
Thank you @lukapecnik for all the hard work.

**Comment by lukapecnik** [comment]
I've added the "examples" folder along with some basic examples on how to use NiaAML Framework.
