### ISSUE TITLE
On the use of unittest

### ISSUE THREAD

**Issue by sisco0** [lukapecnik/NiaAML#2]
Testing scripts are placed and named correctly, but test cases should be written using `unittest` package and  `unittest.TestCase` classes, with the corresponding `assertEqual` or so.

**Comment by lukapecnik** [comment]
@sisco0 test files in this framework are at this point automatically generated and currently will not be a main point of interest. The purpose of tests and which parts of code will actually be tested shall be decided in the later stages of development. However, we will absolutely take `unittest` package into consideration when we reach the stage.

**Comment by lukapecnik** [comment]
Unit testing uses the `unittest` package now.
