### ISSUE TITLE
CSV Data Reader class

### ISSUE THREAD

**Issue by sisco0** [lukapecnik/NiaAML#3]
For this purpose the use of the `panda` package could replace the current implementation.
If the library is able to handle `panda` dataframes instead of X and Y matrices it would be powerful enough as to select, at a next step after reading the dataframe, which columns are input and which columns (in plural) are output.

**Comment by sisco0** [comment]
I mean, maybe it would be the responsibility of the user to prepare the input data into `panda` dataframes.

**Comment by lukapecnik** [comment]
@sisco0 thank you for your suggestion. The use of `panda` package will absolutely be considered in the future stages of framework implementation. The use of matrices is sufficient for early testing, as we still haven't decided on what types of data readers shall be a part of NIAAML Framework.

**Comment by lukapecnik** [comment]
Framework will currently not use `panda` package to read csv files as the current implementation or CSVDataReader is sufficient.

**Comment by lukapecnik** [comment]
Framework version 1.0.0rc1 now uses `pandas` package to handle data. We decided to use it because of the categorical features encoding and easier data handling.
