### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by rhododendrom** [lukapecnik/NiaAML#31]
It seems that installation fails with the recent version.

-----------------------

ERROR: Could not find a version that satisfies the requirement niaaml (from versions: none)
ERROR: No matching distribution found for niaaml

**Comment by lukapecnik** [comment]
hi @rhododendrom,

thank you for reporting this issue. Can you please specify the version of python you are using?

**Comment by rhododendrom** [comment]
Hi,

Thanks for your mail, please see below:

python --version
Python 3.6.9

BR,
r.

**Comment by lukapecnik** [comment]
Hi @rhododendrom,

currently the Python 3.6.x is not supported. However, we may support it in the near future. Please use the NiaAML package with Python version 3.7 or 3.8 for now.

Best regards,
l.

**Comment by firefly-cpp** [comment]
Hi  @rhododendrom 

Good point!

We will try to add support for py 3.6 ASAP.
 
Thank you for reporting this issue.

**Comment by lukapecnik** [comment]
Hi @rhododendrom and @firefly-cpp ,

it turns out there were very minor changes required to support Python 3.6. It should be available now to download using pip as a `rc4`.

Best regards,
l.

**Comment by firefly-cpp** [comment]
Excellent. Thank you @lukapecnik for quick response

**Comment by rhododendrom** [comment]
It works. Thank you for quick reply.

BR,
r
