### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by firefly-cpp** [lukapecnik/NiaAML#34]
Hi @lukapecnik 

In order to support more data scientists, NiaAML conda package might be very beneficial. 

NiaPy also exists as a conda package. [Please check an example of configuration file.](
 https://github.com/NiaOrg/NiaPy/tree/master/conda)

**Comment by lukapecnik** [comment]
Hi @firefly-cpp,

Thank you for your suggestion, NiaAML is now available as conda package.
