### ISSUE TITLE
A non-functional demo could be written

### ISSUE THREAD

**Issue by sisco0** [lukapecnik/NiaAML#4]
At the first step of the project a non-functional demo could be written in the documentation, based on the paper, it could be something like the demo below:

```python
# 1. Read the input file and sepparate input from output columns
df = pandas.read_csv('inputDataFile.csv')
all_inputs = df.iloc[:, 1:]
outputs = df.iloc[:, 0]
# 2. Once the data has been managed, then create a layer style architecture pipeline
pipeline = niaaml.pipeline(
    data_feed = {
        inputs: all_inputs
        outputs: outputs
    },
    feature_selection = {
        algorithms: [niaaml.optim.algorithms.de(parameters) ,niaaml.optim.algorithms.pso(parameters)],
        transforms: [niaaml.transforms.rescaling]
    },
    classifier_selection = {
        algorithms: [
            niaaml.classifiers.mlp(
                depths=range(1,10),
                training_algorithms=[niaaml.optim.algorithms.de(parameters)]
            ),
            niaaml.classifiers.adaboost()]
    }
)
# 3. Run the pipeline and get the resulting model, with the possibility
# of using GPU processing capabilities
devices = niaaml.get_compatible_devices()
optimization = pipeline.optimize(device=devices[0])
# 4. After that, obtain the corresponding model summary
print(optimization.best_pipeline.summary())
```

**Comment by sisco0** [comment]
Please @lukapecnik , could you review if this is intended?

**Comment by lukapecnik** [comment]
@sisco0 thank you for your suggestion. This project is in an early stage of development and it's still being decided what will actually be a part of framework and what will the optimization flow look like. Usage examples will absolutely be provided in the near future.

**Comment by sisco0** [comment]
I am happy to hear from you @lukapecnik . The reason why I would like to have this scheme is for guiding the development of the different modules in order to know how would they interact one with each other and ensure that a _pythonic_ language is used at the creation of the runs.
