### ISSUE TITLE
References

### ISSUE THREAD

**Issue by firefly-cpp** [lukapecnik/NiaAML#40]
For the sake of correctness, please add a reference of original papers for each of the classifiers.

For example:

    r"""Implementation of AdaBoost classifier.
    
    Date:
        2020

    Author:
        Luka Pečnik

    License:
        MIT

    Reference:
	X add a reference X
    
    Documentation:
	X link to the scikit docs X	

    See Also:
        *

**Comment by lukapecnik** [comment]
Hi @firefly-cpp ,

absolutely, I have added references and docs link to all classifiers and other components too.
