### ISSUE TITLE
Example file pipeline.ppln is out of date

### ISSUE THREAD

**Issue by musicinmybrain** [lukapecnik/NiaAML#60]
Trying to run `examples/load_pipeline_object_file.py` results in:

```
ModuleNotFoundError: No module named 'NiaPy'
```

This is because the contents of `examples/exaple_files/pipeline.ppln` were not updated in https://github.com/lukapecnik/NiaAML/pull/49 when other `NiaPy` imports were switched to `niapy`.

I tried simply doing a byte-string replacement of each `NiaPy` occurrence with `niapy` in `pipeline.ppln`, but that wasn’t sufficient:

```
ModuleNotFoundError: No module named 'niapy.algorithms.utility'
```

It looks like, however `pipeline.ppln` was originally created, the process needs to be repeated using a current version of NiaPy.

**Comment by firefly-cpp** [comment]
@lukapecnik

**Comment by lukapecnik** [comment]
Thank you for reporting. Fixed.

**Comment by musicinmybrain** [comment]
Thanks!
